
#
#Modify Create's impact on your terrain
[world]
	#
	#Prevents all worldgen added by Create from taking effect
	disableWorldGen = false

	[world.copper_ore]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 21
		#
		#Range: > 0
		clusterCount = 1
		#
		#Range: > 0
		minHeight = 40
		#
		#Range: > 0
		maxHeight = 96

	[world.copper_ore_ocean]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 15
		#
		#Range: > 0
		clusterCount = 4
		#
		#Range: > 0
		minHeight = 20
		#
		#Range: > 0
		maxHeight = 55

	[world.zinc_ore]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 8
		#
		#Range: > 0
		clusterCount = 1
		#
		#Range: > 0
		minHeight = 55
		#
		#Range: > 0
		maxHeight = 80

	[world.zinc_ore_desert]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 10
		#
		#Range: > 0
		clusterCount = 5
		#
		#Range: > 0
		minHeight = 50
		#
		#Range: > 0
		maxHeight = 85

	[world.limestone]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 128
		#
		#Range: 0.0 ~ 1.0
		clusterChance = 0.03125
		#
		#Range: > 0
		minHeight = 30
		#
		#Range: > 0
		maxHeight = 70

	[world.weathered_limestone]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 128
		#
		#Range: 0.0 ~ 1.0
		clusterChance = 0.03125
		#
		#Range: > 0
		minHeight = 10
		#
		#Range: > 0
		maxHeight = 30

	[world.dolomite]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 128
		#
		#Range: 0.0 ~ 1.0
		clusterChance = 0.015625
		#
		#Range: > 0
		minHeight = 20
		#
		#Range: > 0
		maxHeight = 70

	[world.gabbro]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 128
		#
		#Range: 0.0 ~ 1.0
		clusterChance = 0.015625
		#
		#Range: > 0
		minHeight = 20
		#
		#Range: > 0
		maxHeight = 70

	[world.scoria]
		#
		#Whether to spawn this in your World
		enable = true
		#
		#Range: > 0
		clusterSize = 128
		#
		#Range: 0.0 ~ 1.0
		clusterChance = 0.03125
		#
		#Range: > 0
		minHeight = 0
		#
		#Range: > 0
		maxHeight = 10

